
services:
  minha-api:
    build: .
    ports:
      - "5002:5002"
    networks:
      - cloudflared-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://minha-api:5002
    depends_on:
      - minha-api
    networks:
      - cloudflared-network

networks:
  cloudflared-network:
    driver: bridge
